#4核心，8G
server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
    max-connections: 20000 #最大连接数
    accept-count: 1000 #最大等待队列，如果并发超过21000则直接拒绝
    connection-timeout: 10000
  port: 2006

logging:
  file:
    name: example-order-alibaba-2006.log
  level:
    org.springframework.web: INFO
    com.alibab.cloud.stream.binder.rocketmq: INFO
    io.seata: INFO

spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: caffeine
      limit: 1000
      keyConvertor: fastjson
      expireAfterWriteInMillis: 30000
  remote:
    default:
      type: redis.lettuce
      limit: 1000
      uri: redis://${redis.password}@${redis.host}:${redis.port}/
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      expireAfterWriteInMillis: 40000

mybatis:
  type-aliases-package: com.tangmiyi.future.*.pojo
  mapper-locations: classpath:mapper/*.xml
  #配置驼峰下划线
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

seata:
  enabled: true
  application-id: ${spring.application.name}
  #每个服务分配到的事务组，配置中心搜索*service.vgroupMapping*
  tx-service-group: ${spring.application.name}-tx-group
  enable-auto-data-source-proxy: true
  config:
    type: nacos
    nacos:
      serverAddr: '@nacos.addr@'
      namespace: '@nacos.namespace@'
      group: SEATA_GROUP
      username: '@nacos.username@'
      password: '@nacos.password@'
  registry:
    type: nacos
    nacos:
      application: seata-server
      serverAddr: '@nacos.addr@'
      namespace: '@nacos.namespace@'
      group: SEATA_GROUP
      username: '@nacos.username@'
      password: '@nacos.password@'